<a href="https://colab.research.google.com/github/M-8-ops/M-8-ops/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('TelecomChurn.csv')
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[   0    1   30 ...  207   72    4]
 [   1    2   58 ...   54   82    5]
 [   2    3   47 ...  458    5    9]
 ...
 [ 997  998   48 ...  786   62    3]
 [ 998  999   31 ...   96    7    7]
 [ 999 1000   71 ...  747   46    6]]


In [5]:
print(y)

[ True False  True False False  True  True  True  True False False  True
  True False False  True False False False  True  True False  True  True
  True  True  True False False  True False False  True False  True  True
  True  True False False False  True  True False  True  True False False
 False  True False False  True False False  True False  True False False
 False  True  True  True  True False False  True False False False False
  True  True  True False False False False False False  True False False
 False  True  True  True  True  True False False False False False False
  True False  True  True False  True  True  True False False False  True
  True False  True False  True  True  True  True False False  True  True
 False  True  True False False False False False  True False False  True
  True  True  True  True  True False  True False  True  True  True False
  True  True  True  True False  True False False False  True False  True
 False  True  True False False False  True  True  T

### Encoding categorical data

Label Encoding the "Churn" column

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[1 0 1 0 0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 1 0 1 1 1
 1 0 0 0 1 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 1 1 1 1 0 0 1 0 0 0 0 1 1
 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1
 0 1 1 1 1 0 0 1 1 0 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1
 0 1 0 0 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 0 1 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1 0
 1 0 1 0 0 1 1 1 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 1 1 0 1 1 1
 1 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 0
 0 0 1 0 0 0 1 0 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 1 1 1
 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 1 1 0 1 1 0 0 1 1 1
 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 0 1 1 0 0 0 1 1 0 1
 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 0 1
 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1
 1 1 0 0 1 0 1 0 0 0 0 1 0 1 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 1 1 1 0 0 0 1
 0 1 0 1 0 0 1 1 0 0 0 0 

### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
print(X)

[[   0    1   30 ...  207   72    4]
 [   1    2   58 ...   54   82    5]
 [   2    3   47 ...  458    5    9]
 ...
 [ 997  998   48 ...  786   62    3]
 [ 998  999   31 ...   96    7    7]
 [ 999 1000   71 ...  747   46    6]]


## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
25/25 [==============================] - 1s 2ms/step - loss: 0.7353 - accuracy: 0.5288
Epoch 2/100
25/25 [==============================] - 0s 2ms/step - loss: 0.7176 - accuracy: 0.5263
Epoch 3/100
25/25 [==============================] - 0s 1ms/step - loss: 0.7068 - accuracy: 0.5175
Epoch 4/100
25/25 [==============================] - 0s 1ms/step - loss: 0.7003 - accuracy: 0.5200
Epoch 5/100
25/25 [==============================] - 0s 1ms/step - loss: 0.6961 - accuracy: 0.5238
Epoch 6/100
25/25 [==============================] - 0s 1ms/step - loss: 0.6925 - accuracy: 0.5250
Epoch 7/100
25/25 [==============================] - 0s 1ms/step - loss: 0.6901 - accuracy: 0.5238
Epoch 8/100
25/25 [==============================] - 0s 1ms/step - loss: 0.6881 - accuracy: 0.5375
Epoch 9/100
25/25 [==============================] - 0s 2ms/step - loss: 0.6863 - accuracy: 0.5437
Epoch 10/100
25/25 [==============================] - 0s 1ms/step - loss: 0.6849 - accuracy: 0.5437
Epoch 11/

## Part 4 - Making the predictions and evaluating the model

**Solution**

### Predicting the Test set results

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

7/7 [==============================] - 0s 1ms/step
[[0 0]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 

### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[60 45]
 [51 44]]


0.52